apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: grafana-cinder-retain
provisioner: cinder.csi.openstack.org
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m
  timeout: 20m
  releaseName: grafana
  targetNamespace: monitoring
  install:
    createNamespace: true
  chart:
    spec:
      chart: grafana
      version: "13.2.7"
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    persistence:
      enabled: true
      type: pvc
      storageClassName: grafana-cinder-retain
      size: 5Gi
    deploymentStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
    startupProbe:
      httpGet:
        path: /api/health
        port: grafana
      periodSeconds: 10
      failureThreshold: 120
    progressDeadlineSeconds: 1200

    grafana.ini:
      database:
        wal: true

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            uid: prometheus
            url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            uid: loki
            url: http://loki.monitoring.svc:3100
            access: proxy
          - name: Alertmanager
            type: alertmanager
            uid: alertmanager
            url: http://kube-prometheus-stack-alertmanager.monitoring.svc:9093
            access: proxy
            jsonData:
              implementation: prometheus
