apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: twitter-backend
  namespace: flux-system
spec:
  image: docker.io/joacor7/twitter-api
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: twitter-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: twitter-backend
  filterTags:
    pattern: '^v1$'
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: twitter-backend
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-image-automation
        email: flux-image-automation@users.noreply.github.com
      messageTemplate: 'chore: actualizar imagen del backend Twitter'
    push:
      branch: main
  update:
    path: ./manifests
    strategy: Setters
